version: '3.5'

services:
  db-announcement:
    container_name: db_announcement_container
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: food_announcement_db
      PGDATA: /data/postgres
    volumes:
      - db-announcement:/data/postgres
    ports:
      - "5434:5432"
    networks:
      - common_network
    restart: unless-stopped

  db-request:
    container_name: db_request_container
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: food_request_db
      PGDATA: /data/postgres
    volumes:
      - db-request:/data/postgres
    ports:
      - "5435:5432"
    networks:
      - common_network
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/var/lib/zookeeper
    networks:
      - common_network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - common_network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  food-announcement-service:
    build: ./food-donation-app-donate
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-announcement:5432/food_announcement_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: welcome
    networks:
      - common_network
    depends_on:
      - db-announcement

  food-request-service:
    build: ./food-donation-app-request
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-request:5432/food_request_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: welcome
    networks:
      - common_network
    depends_on:
      - db-request

networks:
  common_network:
    driver: bridge

volumes:
  db-announcement:
  db-request:
  kafka_data:
  zookeeper_data:
