version: '3.5'

services:
  db-user:
    container_name: db_userservice_container
    image: postgis/postgis:14-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: welcome
      POSTGRES_DB: user_service_db
      PGDATA: /data/postgres
    volumes:
      - db-user:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - common_network
    restart: unless-stopped

networks:
  common_network:
    driver: bridge

volumes:
  db-user:
